### ISSUE TITLE
Temporary error message when loading

### ISSUE THREAD

**Issue by benrito** [consumer-reports-digital-lab/thedigitalstandard.org#23]
Hey @tbeck, looks like there's an error message when the endpoint doesn't load, but it also flashes on page load before it loads up the JSON. See screenshot:

![Screen Shot 2020-09-30 at 10 00 31 AM](https://user-images.githubusercontent.com/541325/94695658-2d517e00-0304-11eb-8f99-c6462b86f3fd.png)

Should we do something like a timer, a CSS visibility toggle, or fade it in?

**Comment by tbeck** [comment]
@benrito - I added a CSS fade on page load that fixes this.

**Comment by ginnyfahs** [comment]
This morning I noticed that both https://polite-moon.cloudvent.net/standard/ownership/ and https://polite-moon.cloudvent.net/standard/privacy/ continue to flash a quick "Uh Oh" message before the redirect. It happens too quickly for me to snap a screenshot, but blinks consistently every time. 

Is there a more seamless way to handle? Perhaps a different event trigger?

Big thanks in advance for helping us identify what other options exist --
