### ISSUE TITLE
Request for comments: changing the testName property 

### ISSUE THREAD

**Issue by nlevenson** [consumer-reports-digital-lab/thedigitalstandard.org#35]
Per convo with @benrito this morning, just opening up discussion around a proposed change to the [Digital Standard](https://github.com/TheDigitalStandard/TheDigitalStandard):

The YAML docs currently use the property "testName" to describe the high level focus of the procedures contained within.  However, since many procedures do not exactly describe tests, per se, but rather describe some reasoning or philosophical consideration to be performed on the part of the evaluator, it's probably better to generalize the "testName" property by changing it to "evaluationName."

If this change were to be implemented, are there any concerns or special issues that would break the build process?

**Comment by benrito** [comment]
Any issue @tbeck ?

**Comment by tbeck** [comment]
We have pushed updates to accommodate changes in the DS structure. Closing this issue for now.
