### ISSUE TITLE
Digital Standard content pages broken

### ISSUE THREAD

**Issue by benrito** [consumer-reports-digital-lab/thedigitalstandard.org#46]
Hey @tbeck, since I changed the Org name yesterday these pages broke:

https://thedigitalstandard.org/standard/ownership/?version=v1.2.1
https://thedigitalstandard.org/standard/privacy/?version=v1.2.1
https://thedigitalstandard.org/standard/security/?version=v1.2.1

Can you advise on how to isolate & fix?

**Comment by tbeck** [comment]
Hi Ben,
I can create a PR that you can merge to fix...


https://github.com/consumer-reports-digital-lab/thedigitalstandard.org/pull/47


I can’t think of any other instances of the organization reference, but will continue to look. Let me know if you catch nay others.

Thanks,
Tom


----------------------------------------------------
Tom Beck | Technical Director | Ocupop
www.ocupop.com
Phone : 604.902.1411
Video : ocu.vc/tom
----------------------------------------------------
